repos:
# - repo: https://github.com/jonasbb/pre-commit-latex-hooks
#   rev: v1.2.3
#   hooks:
#     - id: american-eg-ie
#     - id: cleveref-capitalization
#     - id: consistent-spelling
#       args:
#           [
#             "--emph=et al.",
#             "--emph=a priori",
#             "--emph=a posteriori",
#             '--regex=naive=\bna(i|\\"i)ve',
#           ]
#     - id: csquotes
#     - id: ensure-labels-for-sections
#     - id: no-space-in-cite
#     - id: tilde-cite
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-merge-conflict
- repo: local
  hooks:
  - id: latexindent
    name: latexindent
    entry: ./latexindent.sh
    language: script
    # files: \.tex$
    # files: ".*\\.tex$"
    # files: ^volumes/
    files: \.tex$
    # exclude: ^utils/
  - id: latexindent2
    name: latexindent2
    entry: ./latexindent.sh
    language: script
    files: \.tikz$
    # exclude: ^utils/
  - id: check-no-tabs
    name: check-no-tabs
    entry: ./check_no_tabs.py
    language: python
    files: \.tex$